apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "hellospring.name" . }}-rollout
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
        - name: {{ include "hellospring.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: {{ .Values.image.pullPolicy }}
  strategy:
    canary:
      stableService: {{ include "hellospring.name" . }}-active
      canaryService: {{ include "hellospring.name" . }}-canary
      steps:
        - setWeight: 20
        - pause: { duration: 30 }
        - setWeight: 100
      trafficRouting:
        nginx:
	  stableIngress: {{ include "hellospring.name" . }}-ingress
      autoPromotionEnabled: false
