apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "hellospring.name" . }}-rollout
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
        - name: {{ include "hellospring.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: {{ .Values.image.pullPolicy }}
  strategy:
    canary:
      stableService: {{ include "hellospring.name" . }}-active  # 안정 서비스 정의
      canaryService: {{ include "hellospring.name" . }}-canary  # 카나리 서비스 정의
      steps:
        - setWeight: 20  # 첫 번째 배포 시 20%의 트래픽을 새 버전으로 전환
        - pause: { duration: 30 }  # 30초 동안 대기
        - setWeight: 100  # 나머지 80%의 트래픽을 새 버전으로 전환
      trafficRouting:
        nginx:
          stableService: {{ include "hellospring.name" . }}-active  # 안정 서비스 이름
      autoPromotionEnabled: false

