apiVersion: v1
kind: Service
metadata:
  name: {{ include "hellospring.name" . }}-active
  labels:
    app: {{ .Values.labels.app }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 8080
  selector:
    app: {{ .Values.labels.app }}

---

# preview Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hellospring.name" . }}-canary
  labels:
    app: {{ .Values.labels.app }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 8080
  selector:
    app: {{ .Values.labels.app }}
