apiVersion: v1
kind: Service
metadata:
  name: {{ include "hellospring.fullname" . }}
  labels:
    app: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: backend

